name: Testing

on:
  push:
    branches:
      - '*'
    tags:
      - 'v*'
  pull_request:
    branches:
      - '*'
  schedule:
    - cron: "0 13 * * 1"

jobs:
  build-and-test:
    name: Testing (On ${{ matrix.os }}, with MKL ${{ matrix.mkl-version }} from ${{ matrix.channel }} )
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: False
      matrix:
        os: [ubuntu-latest, macos-12, windows-latest]
        channel: ['conda-forge', 'defaults']
        mkl-version: ['2023', '2024']
        exclude:
          - os: macos-12
            mkl-version: "2024"

    steps:
    - uses: actions/checkout@v4
    - name: Setup Conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        mamba-version: '*'
        channels: conda-forge, defaults
        channel-priority: true
        activate-environment: mkl_test

    - name: Conda information
      run: |
        conda info
        conda list
        conda config --show

    - name: Create environment
      run: |
        conda install --quiet --yes --channel ${{matrix.channel}} mkl=${{ matrix.mkl-version }} mkl-devel pkg-config meson ninja

    - name: build the test program
      run: |
        meson setup build ${{ matrix.os == 'windows-latest' && '--vsenv' || ''}}
        ninja -C build

    - name: Attempt to run
        ls -al build